import { Customer, Item, JobTemplate, Vendor, VendorItemPriceHistory } from './types';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust_1',
    name: 'Sarah Johnson',
    address: '123 Maple Ave, Springfield, IL 62704',
    phone: '(555) 123-4567',
  },
  {
    id: 'cust_2',
    name: 'Michael Chen',
    address: '456 Oak St, Springfield, IL 62704',
    phone: '(555) 987-6543',
  },
  {
    id: 'cust_3',
    name: 'Riverside Apartments',
    address: '789 River Rd, Springfield, IL 62704',
    phone: '(555) 456-7890',
  },
];

export const JOB_TEMPLATES: JobTemplate[] = [
  {
    jobType: 'AC Capacitor Replacement',
    flatRateLow: 250,
    flatRateHigh: 450,
    typicalMaterials: ['Capacitor', 'Contactors'],
    typicalLaborHours: 0.75,
  },
  {
    jobType: 'Drain Cleaning (Main Line)',
    flatRateLow: 175,
    flatRateHigh: 350,
    typicalMaterials: ['Bio-Clean', 'Snake Rental'],
    typicalLaborHours: 1.5,
  },
  {
    jobType: 'Gas Water Heater Replacement (40/50 gal)',
    flatRateLow: 1800,
    flatRateHigh: 3200,
    typicalMaterials: ['Water Heater', 'Flex Lines', 'Expansion Tank'],
    typicalLaborHours: 4,
  },
  {
    jobType: 'AC Tune-up / Inspection',
    flatRateLow: 99,
    flatRateHigh: 199,
    typicalMaterials: ['Filter', 'Coil Cleaner'],
    typicalLaborHours: 1.5,
  },
  {
    jobType: 'Toilet Repair / Flapper & Fill Valve',
    flatRateLow: 185,
    flatRateHigh: 325,
    typicalMaterials: ['Fill Valve', 'Flapper', 'Supply Line'],
    typicalLaborHours: 1,
  },
  {
    jobType: 'Garbage Disposal Replacement',
    flatRateLow: 350,
    flatRateHigh: 650,
    typicalMaterials: ['Disposal Unit', 'Plumber\'s Putty'],
    typicalLaborHours: 1.5,
  },
];

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'vendor_1',
    name: 'Midwest HVAC Supply',
    contactName: 'Dana Brooks',
    email: 'orders@midwesthvac.example',
    phone: '(555) 221-0184',
    category: 'HVAC',
    paymentTerms: 'Net 30',
    leadTimeDays: 1,
    preferred: true,
    reliabilityScore: 92,
    notes: 'Fast counter pickup for capacitors, contactors, filters, and tune-up consumables.',
    aliases: [
      { id: 'alias_1', vendorId: 'vendor_1', name: 'Midwest HVAC' },
      { id: 'alias_2', vendorId: 'vendor_1', name: 'MHS Counter' },
    ],
    createdAt: '2026-04-01T14:00:00.000Z',
    updatedAt: '2026-04-01T14:00:00.000Z',
  },
  {
    id: 'vendor_2',
    name: 'Prairie Pipe & Fixture',
    contactName: 'Luis Martin',
    email: 'counter@prairiepipe.example',
    phone: '(555) 640-7732',
    category: 'Plumbing',
    paymentTerms: 'Due on receipt',
    leadTimeDays: 2,
    preferred: true,
    reliabilityScore: 88,
    notes: 'Good source for water heaters, supply lines, valves, and common toilet repair kits.',
    aliases: [
      { id: 'alias_3', vendorId: 'vendor_2', name: 'Prairie Pipe' },
    ],
    createdAt: '2026-04-02T15:30:00.000Z',
    updatedAt: '2026-04-02T15:30:00.000Z',
  },
  {
    id: 'vendor_3',
    name: 'ToolShare Rentals',
    contactName: 'Marissa Kim',
    email: 'dispatch@toolshare.example',
    phone: '(555) 707-1199',
    category: 'Rental',
    paymentTerms: 'Card on file',
    leadTimeDays: 0,
    preferred: false,
    reliabilityScore: null,
    notes: 'Short-notice drain machines, lift rentals, and specialty tools.',
    aliases: [
      { id: 'alias_4', vendorId: 'vendor_3', name: 'ToolShare' },
    ],
    createdAt: '2026-04-03T16:45:00.000Z',
    updatedAt: '2026-04-03T16:45:00.000Z',
  },
];

export const MOCK_ITEMS: Item[] = [
  {
    id: 'item_1',
    canonicalName: 'Run Capacitor',
    category: 'HVAC',
    unit: 'each',
    aliases: ['Capacitor', 'Dual run cap'],
    createdAt: '2026-04-01T14:05:00.000Z',
    updatedAt: '2026-04-01T14:05:00.000Z',
  },
  {
    id: 'item_2',
    canonicalName: '40 Gallon Gas Water Heater',
    category: 'Plumbing',
    unit: 'each',
    aliases: ['Gas water heater', '40 gal heater'],
    createdAt: '2026-04-02T15:35:00.000Z',
    updatedAt: '2026-04-02T15:35:00.000Z',
  },
  {
    id: 'item_3',
    canonicalName: 'Drain Machine Rental',
    category: 'Rental',
    unit: 'day',
    aliases: ['Snake rental', 'Drain snake'],
    createdAt: '2026-04-03T16:50:00.000Z',
    updatedAt: '2026-04-03T16:50:00.000Z',
  },
  {
    id: 'item_4',
    canonicalName: 'Toilet Fill Valve',
    category: 'Plumbing',
    unit: 'each',
    aliases: ['Fill valve', 'Toilet repair valve'],
    createdAt: '2026-04-04T13:15:00.000Z',
    updatedAt: '2026-04-04T13:15:00.000Z',
  },
];

export const MOCK_VENDOR_ITEM_PRICE_HISTORY: VendorItemPriceHistory[] = [
  {
    id: 'price_watch_up_current',
    vendorId: 'vendor_1',
    itemId: 'item_1',
    price: 39.5,
    quantity: 1,
    currency: 'USD',
    date: '2026-04-11T14:30:00.000Z',
    sourceType: 'capture',
    sourceId: 'q_seed_capacitor_watch_up',
    notes: 'Recent capacitor counter pickup for watch demo.',
  },
  {
    id: 'price_1',
    vendorId: 'vendor_1',
    itemId: 'item_1',
    price: 34.5,
    quantity: 1,
    currency: 'USD',
    date: '2026-04-07T14:30:00.000Z',
    sourceType: 'capture',
    sourceId: 'q_seed_capacitor',
    notes: 'Counter pickup for AC no-cool call.',
  },
  {
    id: 'price_1_prior',
    vendorId: 'vendor_1',
    itemId: 'item_1',
    price: 31.75,
    quantity: 1,
    currency: 'USD',
    date: '2026-03-20T14:30:00.000Z',
    sourceType: 'capture',
    sourceId: 'q_seed_capacitor_prior',
    notes: 'Previous capacitor counter pickup.',
  },
  {
    id: 'price_watch_down_current',
    vendorId: 'vendor_2',
    itemId: 'item_2',
    price: 575,
    quantity: 1,
    currency: 'USD',
    date: '2026-04-11T16:10:00.000Z',
    sourceType: 'work_order',
    sourceId: 'WO-seed-water-heater-watch-down',
    notes: 'Recent water heater purchase for watch demo.',
  },
  {
    id: 'price_2',
    vendorId: 'vendor_2',
    itemId: 'item_2',
    price: 642,
    quantity: 1,
    currency: 'USD',
    date: '2026-04-08T16:10:00.000Z',
    sourceType: 'work_order',
    sourceId: 'WO-seed-water-heater',
    notes: 'Standard atmospheric vent unit.',
  },
  {
    id: 'price_2_prior',
    vendorId: 'vendor_2',
    itemId: 'item_2',
    price: 675,
    quantity: 1,
    currency: 'USD',
    date: '2026-03-28T16:10:00.000Z',
    sourceType: 'work_order',
    sourceId: 'WO-seed-water-heater-prior',
    notes: 'Previous water heater purchase.',
  },
  {
    id: 'price_3',
    vendorId: 'vendor_3',
    itemId: 'item_3',
    price: 72,
    quantity: 1,
    currency: 'USD',
    date: '2026-04-09T12:25:00.000Z',
    sourceType: 'manual',
    sourceId: 'manual_seed_toolshare',
    notes: 'One-day rental rate.',
  },
  {
    id: 'price_3_prior',
    vendorId: 'vendor_3',
    itemId: 'item_3',
    price: 72,
    quantity: 1,
    currency: 'USD',
    date: '2026-03-26T12:25:00.000Z',
    sourceType: 'manual',
    sourceId: 'manual_seed_toolshare_prior',
    notes: 'Previous one-day rental rate.',
  },
  {
    id: 'price_3_older',
    vendorId: 'vendor_3',
    itemId: 'item_3',
    price: 70,
    quantity: 1,
    currency: 'USD',
    date: '2026-03-10T12:25:00.000Z',
    sourceType: 'manual',
    sourceId: 'manual_seed_toolshare_older',
    notes: 'Older one-day rental rate.',
  },
];
